### ISSUE TITLE
auto-do-task error

### ISSUE THREAD

**Issue by rahadian** [smart-airdrop/blum-claimer#4]
If auto-do-task set to true, error occurred "Error: 'title'"
Please fix it. Thanks
![Screenshot_20240907_074241](https://github.com/user-attachments/assets/3d6117d6-af3b-4d65-b251-eba7952dd219)

**Comment by smart-airdrop** [comment]
Error fixed. Please get the lastest version

**Comment by rahadian** [comment]
nice thanks
